

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass1122
      POSTGRES_DB: cactusify_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80' # pgAdmin UI accessible at localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cactusify.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pgdata:
